<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-22T00:27:44 IST" name="Suite" finished-at="2024-09-22T00:28:14 IST" duration-ms="30046">
    <groups>
      <group name="NegativeScenario">
        <method signature="ErrorValidationsTest.blankusername_blankpassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" name="blankusername_blankpassword" class="com.remedi.test.ErrorValidationsTest"/>
      </group> <!-- NegativeScenario -->
    </groups>
    <test started-at="2024-09-22T00:27:44 IST" name="errorvalidationsTest" finished-at="2024-09-22T00:28:14 IST" duration-ms="30046">
      <class name="com.remedi.test.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:44 IST" name="launchApplication" finished-at="2024-09-22T00:27:48 IST" duration-ms="4910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="blankUsername_validpassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:48 IST" name="blankUsername_validpassword" finished-at="2024-09-22T00:27:49 IST" duration-ms="1007" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please Provide Username] but found [Please Provide Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please Provide Username] but found [Please Provide Password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.remedi.test.ErrorValidationsTest.blankUsername_validpassword(ErrorValidationsTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankUsername_validpassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:49 IST" name="tearDown" finished-at="2024-09-22T00:27:50 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:50 IST" name="launchApplication" finished-at="2024-09-22T00:27:53 IST" duration-ms="3452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="blankUsername_validpassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:53 IST" name="blankUsername_validpassword" finished-at="2024-09-22T00:27:54 IST" duration-ms="1027" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please Provide Username] but found [Please Provide Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please Provide Username] but found [Please Provide Password]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.remedi.test.ErrorValidationsTest.blankUsername_validpassword(ErrorValidationsTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankUsername_validpassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:55 IST" name="tearDown" finished-at="2024-09-22T00:27:55 IST" duration-ms="152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:55 IST" name="launchApplication" finished-at="2024-09-22T00:27:57 IST" duration-ms="2571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="blankusername_blankpassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:57 IST" name="blankusername_blankpassword" finished-at="2024-09-22T00:27:58 IST" duration-ms="961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankusername_blankpassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:58 IST" name="tearDown" finished-at="2024-09-22T00:27:59 IST" duration-ms="183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:27:59 IST" name="launchApplication" finished-at="2024-09-22T00:28:03 IST" duration-ms="4697" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="invalidUsername_validPassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:03 IST" name="invalidUsername_validPassword" finished-at="2024-09-22T00:28:05 IST" duration-ms="1447" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUsername_validPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:05 IST" name="tearDown" finished-at="2024-09-22T00:28:05 IST" duration-ms="199" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:05 IST" name="launchApplication" finished-at="2024-09-22T00:28:07 IST" duration-ms="2557" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validUsername_blankpassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:07 IST" name="validUsername_blankpassword" finished-at="2024-09-22T00:28:08 IST" duration-ms="915" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUsername_blankpassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:08 IST" name="tearDown" finished-at="2024-09-22T00:28:08 IST" duration-ms="94" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:08 IST" name="launchApplication" finished-at="2024-09-22T00:28:12 IST" duration-ms="3670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validUsername_invalidPassword()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:12 IST" name="validUsername_invalidPassword" finished-at="2024-09-22T00:28:13 IST" duration-ms="1228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUsername_invalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.remedi.test.ErrorValidationsTest@723ca036]" started-at="2024-09-22T00:28:13 IST" name="tearDown" finished-at="2024-09-22T00:28:14 IST" duration-ms="204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.remedi.test.ErrorValidationsTest -->
    </test> <!-- errorvalidationsTest -->
  </suite> <!-- Suite -->
</testng-results>
